#!/bin/bash

if [ -f /etc/default/kazoo ]; then
	. /etc/default/kazoo
fi

RETVAL=0
NAME=kazoo-applications
USER=${KAZOO_USER:-kazoo}
BIN_FILE=${BIN_FILE:-/opt/kazoo/bin/kazoo}
export HOME=${KAZOO_ROOT:-/opt/kazoo}
export VMARGS_PATH=${KAZOO_VMARGS:-/etc/kazoo/core/vm.args}

if [ -f /etc/sysconfig/kazoo ]; then
	. /etc/sysconfig/kazoo
fi

if [ "${NAME}" == "kazoo-applications" ]; then
	NAME="kazoo_apps"
else
	NAME=${NAME#*-}
fi

export NAME_ARG="-name ${NAME}"

prepare() {
	mkdir -p /tmp/erl_pipes/${NAME}
	chown -R ${USER} /tmp/erl_pipes/${NAME}
	mkdir -p /var/log/kazoo
	chown -R ${USER} /var/log/kazoo
	chown -R ${USER} /opt/kazoo /opt/kazoo/.*
}

start() {
	cd ${HOME}

	if sudo -u ${USER} ${BIN_FILE} pid > /dev/null 2>&1; then
		echo "Kazoo ${NAME} is already running!"
		RETVAL=1
		return
	fi

	export CODE_LOADING_MODE=interactive
	set -- ${BIN_FILE} "$@"
	if [ "$(whoami)" == "${USER}" ]; then
		exec "$@"
	else
		exec sudo -u ${USER} "$@"
	fi
	RETVAL=$?

	if [ ${RETVAL} -ne 0 ]; then
		echo "Failed to start Kazoo ${NAME}!"
		RETVAL=1
	fi
}

stop() {
	cd ${HOME}

	sudo -u ${USER} ${BIN_FILE} stop

	if sudo -u ${USER} ${BIN_FILE} pid > /dev/null 2>&1; then
		echo "Failed to stop Kazoo ${NAME}!"
		RETVAL=1
	fi
}

restart() {
	stop
	start
}

status() {
	cd ${HOME}

	sudo -u ${USER} ${BIN_FILE} eval 'kz_nodes:status().' | sed \$d
	RETVAL=$?
}

connect() {
	cd ${HOME}

	COOKIE=`sudo -u ${USER} ${BIN_FILE} eval 'erlang:get_cookie()'`
	export COOKIE_ARG="-setcookie ${COOKIE}"

	sudo -u ${USER} ${BIN_FILE} remote_console
	RETVAL=$?
}

attach() {
	cd ${HOME}

	echo "WARNING: You are now directly attached to the running ${NAME} Erlang node."
	echo "   It is safer to use: $0 connect"
	sudo -u ${USER} ${BIN_FILE} attach
	RETVAL=$?
}

ping() {
	cd ${HOME}

	COOKIE=`sudo -u ${USER} ${BIN_FILE} eval 'erlang:get_cookie()'`
	export COOKIE_ARG="-setcookie ${COOKIE}"

	sudo -u ${USER} ${BIN_FILE} ping
	RETVAL=$?
}

pid() {
	cd ${HOME}

	COOKIE=`sudo -u ${USER} ${BIN_FILE} eval 'erlang:get_cookie()'`
	export COOKIE_ARG="-setcookie ${COOKIE}"

	sudo -u ${USER} ${BIN_FILE} pid
	RETVAL=$?
}

case "$1" in
	prepare)
		prpeare
		;;
	start)
		start "start"
		;;
	foreground)
	   start "foreground"
	   ;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	status)
		status
		;;
	connect)
		connect
		;;
	attach)
	   attach
	   ;;
	ping)
	   ping
	   ;;
	pid)
	   pid
	   ;;
	*)
		echo "Usage: $0 (prpeare|start|foreground|stop|restart|status|connect|attach|ping|pid)"
		RETVAL=1
esac

exit ${RETVAL}