#!/bin/sh

sql_db_pre_setup() {
cat << EOF

PRAGMA foreign_keys=OFF;
PRAGMA wal=on;
PRAGMA journal_mode=WAL;

EOF
}

sql_setup() {
 DB_KAZOO_LOCATION=${DB_KAZOO_LOCATION:-/etc/kamailio/db}
 mkdir -p ${DB_KAZOO_LOCATION} 
 KazooDB ${DB_KAZOO_LOCATION}/kazoo.db < $1
}

sql_header() {
cat << EOF
EOF
}

sql_extra_tables() {
cat << EOF
CREATE TABLE active_watchers_log (
    id INTEGER PRIMARY KEY NOT NULL,
    presentity_uri VARCHAR(128) NOT NULL COLLATE NOCASE,
    watcher_username VARCHAR(64) NOT NULL COLLATE NOCASE,
    watcher_domain VARCHAR(64) NOT NULL COLLATE NOCASE,
    to_user VARCHAR(64) NOT NULL COLLATE NOCASE,
    to_domain VARCHAR(64) NOT NULL COLLATE NOCASE,
    event VARCHAR(64) DEFAULT 'presence' NOT NULL,
    callid VARCHAR(255) NOT NULL,
    time INTEGER NOT NULL,
    result INTEGER NOT NULL,
    sent_msg BLOB NOT NULL,
    received_msg BLOB NOT NULL,
    user_agent VARCHAR(255) DEFAULT '' COLLATE NOCASE,
    CONSTRAINT active_watchers_active_watchers_log_idx UNIQUE (presentity_uri, watcher_username, watcher_domain, event)
    );
EOF
}

sql_footer() {
cat << EOF
EOF
}
