#!/bin/sh

sql_db_pre_setup() {
cat << EOF
START TRANSACTION;
EOF
}

sql_setup() {
cat << EOF
EOF
}

sql_header() {
cat << EOF
EOF
}

sql_extra_tables() {
cat << EOF
CREATE TABLE active_watchers_log (
    id SERIAL PRIMARY KEY NOT NULL,
    presentity_uri VARCHAR(128) NOT NULL,
    watcher_username VARCHAR(64) NOT NULL,
    watcher_domain VARCHAR(64) NOT NULL,
    to_user VARCHAR(64) NOT NULL,
    to_domain VARCHAR(64) NOT NULL,
    event VARCHAR(64) DEFAULT 'presence' NOT NULL,
    callid VARCHAR(255) NOT NULL,
    time INTEGER NOT NULL,
    result INTEGER NOT NULL,
    sent_msg BLOB NOT NULL,
    received_msg BLOB NOT NULL,
    user_agent VARCHAR(255) DEFAULT '' NOT NULL,
    CONSTRAINT active_watchers_active_watchers_log_idx UNIQUE (presentity_uri, watcher_username, watcher_domain, event)
);

CREATE TABLE tmp_probe(
  event TEXT,
  presentity_uri TEXT,
  action INT
);

CREATE TABLE auth_cache(
  id INT,
  key_name TEXT,
  key_type INT,
  value_type INT,
  key_value TEXT,
  expires INT
);

CREATE TABLE block_cache(
  id INT,
  key_name TEXT,
  key_type INT,
  value_type INT,
  key_value TEXT,
  expires INT
);

CREATE TABLE keepalive (
  id INTEGER PRIMARY KEY NOT NULL,
  contact VARCHAR(512) NOT NULL,
  received VARCHAR(32) NOT NULL,
  sockinfo VARCHAR(128) NOT NULL,
  time_inserted TIMESTAMP NOT NULL DEFAULT 0,
  time_sent TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  slot INTEGER NOT NULL,
  selected INTEGER DEFAULT 0,
  failed INTEGER DEFAULT 0,
  CONSTRAINT keepalive_idx UNIQUE (contact),
  CONSTRAINT keepalive_idx_2 UNIQUE (slot, failed, contact)
);

CREATE TABLE matrix (
 first INTEGER NOT NULL,
 second SMALLINT NOT NULL,
 res INTEGER NOT NULL
);
EOF
}

sql_footer() {
cat << EOF
ALTER TABLE location_attrs MODIFY avalue varchar(512);
EOF
}
