#!/bin/sh

sql_db_pre_setup() {
cat << EOF
EOF
}

sql_setup() {
}

sql_header() {
cat << EOF
EOF
}

sql_extra_tables() {
cat << EOF
-- Please add MySQL commnad for extra tables
-- Need to add "active_watchers_log"
EOF
}

sql_footer() {
cat << EOF
ALTER TABLE location_attrs ALTER COLUMN avalue TYPE varchar(512);
EOF
}
